'testcase_path': 'G:\\pytest_auto_uitest_apitest\\case/api/excel_data\\demo01.xls'
'emvironment': 'environment_115'
'login_user_on_off': 'zhangtao115'
'api_host': 'http://192.168.0.115:10007'
'base_host': 'http://192.168.0.115:10005'
'login_host': '/uaa/oauth/token'
'login_usernaem': 'уелн'
'login_data': {'username': 'уелн', 'mobile': 15382112620, 'password': 'e64b78fc3bc91bcbc7dc232ba8ec59e0', 'account_type': 'mobile', 'grant_type': 'password', 'scope': 'trust', 'client_secret': '2c27867ba8b35dedbde7361f8ffb704d', 'client_id': 'saas_op'}
'tester': 'уелн'
'delete_old_report': 'off'
'input_report': 'off'
'delete_report_on_off': 'off'
'save_report_on_off': 'off'
'email_on_off': 'off'
'open_report_on_off': 'off'
'send_dingding_on_off': 'off'